name: Deploy nian.ro

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to nian.ro
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
      
      - name: ðŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # FARA SLASH la inceput! Asta e cheia.
          server-dir: cv.nian.ro/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .gitignore
            .github/**

      - name: ðŸ”„ Trigger Restart
        run: |
          mkdir -p tmp
          echo "restart" > tmp/restart.txt
      
      - name: ðŸš€ Upload Restart Trigger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: cv.nian.ro/tmp/
          local-dir: ./tmp/